apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: kube-prometheus-stack
  includeCRDs: True # turn on when first time installation
  valuesMerge: merge
  ValuesFile: values.yaml
  # definition: https://github.com/kubernetes-sigs/kustomize/blob/672c751715be7dd0b43b4a2fce956c84452e0db9/api/types/helmchartargs.go#L61
  releaseName: kube-prometheus-stack
  namespace: monitoring
  version: 56.0.1
  repo: https://prometheus-community.github.io/helm-charts
