apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: jaeger-operator # chart name
  includeCRDs: True # turn on when first time installation
  releaseName: jaegertracing
  namespace: monitoring
  version: v2.50.1
  repo: https://jaegertracing.github.io/helm-charts
  valuesMerge: merge
  ValuesFile: values.yaml
