apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- accesslog.yaml
helmCharts:
- name: base # CRD
  includeCRDs: True # turn on when first time installation
  releaseName: istio
  version: 1.20.2
  repo: https://istio-release.storage.googleapis.com/charts
- name: istiod # chart name
  includeCRDs: True # turn on when first time installation
  releaseName: istio
  namespace: istio-system
  version: 1.20.2
  repo: https://istio-release.storage.googleapis.com/charts
- name: gateway # chart name
  includeCRDs: True # turn on when first time installation
  releaseName: istio-gateway
  namespace: istio-system
  version: 1.20.2
  repo: https://istio-release.storage.googleapis.com/charts
