connectors:
  spanmetrics: null
exporters:
  debug: {}
  logging: {}
  otlp:
    endpoint: 'jaeger-all-in-one-collector:4317'
    tls:
      insecure: true
  otlphttp/prometheus:
    endpoint: http://kube-prometheus-stack-prometheus.monitoring:9090/api/v1/otlp
    tls:
      insecure: true
extensions:
  health_check: {}
processors:
  batch: {}
  filter/ottl:
    error_mode: ignore
    metrics:
      metric:
      - name == "rpc.server.duration"
  k8sattributes:
    extract:
      metadata:
      - k8s.namespace.name
      - k8s.deployment.name
      - k8s.statefulset.name
      - k8s.daemonset.name
      - k8s.cronjob.name
      - k8s.job.name
      - k8s.node.name
      - k8s.pod.name
      - k8s.pod.uid
      - k8s.pod.start_time
    passthrough: false
    pod_association:
    - sources:
      - from: resource_attribute
        name: k8s.pod.ip
    - sources:
      - from: resource_attribute
        name: k8s.pod.uid
    - sources:
      - from: connection
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  resource:
    attributes:
    - action: insert
      from_attribute: k8s.pod.uid
      key: service.instance.id
  transform:
    metric_statements:
    - context: metric
      statements:
      - set(description, "") where name == "queueSize"
      - set(description, "") where name == "rpc.server.duration"
      - set(description, "") where name == "http.client.duration"
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        cors:
          allowed_origins:
          - http://*
          - https://*
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
      - job_name: opentelemetry-collector
        scrape_interval: 10s
        static_configs:
        - targets:
          - 0.0.0.0:8888
  zipkin:
    endpoint: 0.0.0.0:9411
service:
  extensions:
  - health_check
  pipelines:
    logs:
      exporters:
      - debug
      processors:
      - k8sattributes
      - memory_limiter
      - batch
      receivers:
      - otlp
    metrics:
      exporters:
      - otlphttp/prometheus
      - debug
      processors:
      - k8sattributes
      - memory_limiter
      - filter/ottl
      - transform
      - resource
      - batch
      receivers:
      - otlp
      - spanmetrics
    traces:
      exporters:
      - otlp
      - debug
      - spanmetrics
      processors:
      - k8sattributes
      - memory_limiter
      - resource
      - batch
      receivers:
      - otlp
      - jaeger
      - zipkin
  telemetry:
    metrics:
      address: 0.0.0.0:8888
