apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: opentelemetry-operator
  includeCRDs: True # turn on when first time installation
  releaseName: open-telemetry
  namespace: monitoring
  version: 0.46.0
  repo: https://open-telemetry.github.io/opentelemetry-helm-charts
