apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otel-ingress-cert
  namespace: istio-system
spec:
  secretName: otel-ingress-cert
  issuerRef:
    name: letsencrypt-production-istio
    kind: ClusterIssuer
  dnsNames:
  - otel.example.com
